"""add nyaa in bangumi

Revision ID: 0000e79a0e32
Revises: cb7650cd6a4d
Create Date: 2018-02-25 12:01:36.224651

"""

# revision identifiers, used by Alembic.
revision = '0000e79a0e32'
down_revision = 'cb7650cd6a4d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bangumi', sa.Column('nyaa', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bangumi', 'nyaa')
    # ### end Alembic commands ###
