"""add creater and maintainer and alert_timeout in bangumi table

Revision ID: 00a9ac502dd3
Revises: 875ae1099af9
Create Date: 2017-09-04 20:43:12.763509

"""

# revision identifiers, used by Alembic.
revision = '00a9ac502dd3'
down_revision = '875ae1099af9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bangumi', sa.Column('alert_timeout', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('bangumi', sa.Column('created_by_uid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('bangumi', sa.Column('maintained_by_uid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bangumi', 'maintained_by_uid')
    op.drop_column('bangumi', 'created_by_uid')
    op.drop_column('bangumi', 'alert_timeout')
    # ### end Alembic commands ###
