"""add column of watch_progress, alter last_watch_position column data type

Revision ID: 126d03f9641b
Revises: f435b0c46cc2
Create Date: 2016-10-22 18:39:06.466005

"""

# revision identifiers, used by Alembic.
revision = '126d03f9641b'
down_revision = 'f435b0c46cc2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_progress', sa.Column('percentage', sa.Float(), nullable=True))
    op.alter_column('watch_progress', column_name='last_watch_position', type_=sa.Float)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_progress', 'percentage')
    op.alter_column('watch_progress', column_name='last_watch_position', type_=sa.Integer)
    ### end Alembic commands ###
