"""add creater and maintainer information in bangumi table

Revision ID: 35b13c2edfa4
Revises: 875ae1099af9
Create Date: 2017-09-03 19:53:50.631677

"""

# revision identifiers, used by Alembic.
revision = '35b13c2edfa4'
down_revision = '875ae1099af9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bangumi', sa.Column('created_by_uid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('bangumi', sa.Column('maintained_by_uid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bangumi', 'maintained_by_uid')
    op.drop_column('bangumi', 'created_by_uid')
    # ### end Alembic commands ###
