"""add column update_time and check_time in favorites table

Revision ID: 58c8b6f3c017
Revises: 7246a4b97f54
Create Date: 2018-10-23 18:17:06.455522

"""

# revision identifiers, used by Alembic.
revision = '58c8b6f3c017'
down_revision = '7246a4b97f54'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('check_time', sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()))
    op.add_column('favorites', sa.Column('update_time', sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'update_time')
    op.drop_column('favorites', 'check_time')
    # ### end Alembic commands ###
