"""add column of watch_progress

Revision ID: 88b5c888fee5
Revises: f435b0c46cc2
Create Date: 2016-10-22 14:20:53.644990

"""

# revision identifiers, used by Alembic.
revision = '88b5c888fee5'
down_revision = 'f435b0c46cc2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_progress', sa.Column('percentage', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_progress', 'percentage')
    ### end Alembic commands ###
