"""add delete_mark on bangumi table and episode table, add task table

Revision ID: 93206f1acf90
Revises: 1946e41f3c28
Create Date: 2017-04-13 15:51:53.503496

"""

# revision identifiers, used by Alembic.
revision = '93206f1acf90'
down_revision = '1946e41f3c28'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'bangumi', sa.Column('delete_mark', sa.TIMESTAMP(), nullable=True))
    op.add_column(u'episodes', sa.Column('delete_mark', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'episodes', 'delete_mark')
    op.drop_column(u'bangumi', 'delete_mark')
    op.drop_table('task')
    # ### end Alembic commands ###
