"""add type column in Bangumi

Revision ID: f0fe71ca3d01
Revises: 126d03f9641b
Create Date: 2017-01-16 19:04:07.059148

"""

# revision identifiers, used by Alembic.
revision = 'f0fe71ca3d01'
down_revision = '126d03f9641b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bangumi', sa.Column('type', sa.Integer(), nullable=False, server_default='2'))
    op.alter_column('bangumi', 'type', server_default=None)

    op.add_column('bangumi', sa.Column('libyk_so', sa.TEXT(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bangumi', 'type')
    op.drop_column('bangumi', 'libyk_so')
    ### end Alembic commands ###
