"""Add ServerSession table

Revision ID: f4413be17efa
Revises: f798deb267f8
Create Date: 2016-10-05 21:17:22.138637

"""

# revision identifiers, used by Alembic.
revision = 'f4413be17efa'
down_revision = 'f798deb267f8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_session',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', sa.TEXT(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_session')
    ### end Alembic commands ###
